<?php 
/** 
 *
 * Short File Description (Required) 
 * 
 * Long File Description. This file has the package, subpackage and category tags out of order
 *
 * 
 * PHP version 5
 *
 * @version		$Id 			$					[required] 
 * @package		Joomla.Framework
 * @subpackage	ThisExt
 * @category	Joomla
 * @author		Paladin <arlen.walker@gmail.com>
 * @copyright	Copyright (C) 2005 - 2009 Open Source Matters, Inc. All rights reserved. 
 * @copyright	Bad copyright format 
 * @license		GNU General Public License version 2 or later; see LICENSE.txt 
 * @license		Extra licence GNU General Public License version 2 or later; see LICENSE.txt 
 * @link		http://www.joomla.org/				[Optional, core must link to Joomla URL] 
 * @since		1.0									[Optional] 
 * @deprecated	1.5									[Optional] 
 * @deprecated	1.5									[Bad] 
 * @uses											[Optional] 
 * @example		path/to/example.php					[Optional] 
 * @filesource										[Optional] 
 * @internal										[Optional] 
 * @final											[Optional, as PHP5 subsumes it] 
 * @todo											[Optional] 
 */ 

/** 
 * Expecting to be ignored because it's not part of the file comment
 * 
 */ 
?>